name: sysinfo-mqtt
vendor: Mark Wolfe <mark@wolfe.id.au>
architecture: amd64,armhf
icon: meta/sysmon.svg
source: https://github.com/wolfeidau/sysinfo_mqtt
version: 1.0.0
services:
 - name: sysinfo-mqtt
   description: "sysinfo-mqtt: System monitor which publishes info over MQTT"
   start: ./bin/sysinfo_mqtt